source 'https://gitlab.linphone.org/BC/public/podspec.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '12.0'

target 'MifoneSdkNative_Example' do
  pod 'MifoneSdkNative', :path => '../'
  pod 'SAMKeychain'
  pod 'Alamofire', '~> 5.2'
  pod 'QuickTableViewController'
  pod 'Swinject'

end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end
